spring.application.name=admin-service
# Tell Spring where the database is
spring.datasource.url=jdbc:postgresql://localhost:5432/justask_db
spring.datasource.username=admin
spring.datasource.password=rootpassword

# Tell Spring to automatically create tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Show the SQL queries in the IntelliJ console so you can see what it's doing
spring.jpa.show-sql=true